---
- hosts: local

  vars:
    config: "{{ config | default('default') }}"

  vars_files:
    - "{{ config }}.config.yml"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: zanmarolt.ohmyzsh
      tags: ['ohmyzsh']
    - role: zanmarolt.nvm
      tags: ['nvm']
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
