---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true
configure_tmux: true

# User's parent folder
users_folder: "/Users"

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Safari
  - TV
  - Podcasts
  - 'App Store'
  - Messages
  - Maps
  - Music
  - Photos
  - Podcasts
  - FaceTime
  - 'Feedback Assistant'
  - Contacts
  - Reminders
  - Notes
  - Launchpad
  - 'System Preferences'
  - 'Self Service'
  - 'Apple@SAP'


dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 4

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ZanMarolt/dots.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .alias
  - .exports
  - .gitconfig

homebrew_taps:
  - github/gh

homebrew_installed_packages:
  - ansible
  - python
  - sqlite
  - wget
  - magic-wormhole
  - ripgrep
  - tmux
  - wakeonlan
  - tig
  - fzf
  - git
  - gh
  - gpg
  - nvm

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - keepassxc
  - obsidian
  - rancher
  - firefox
  - google-chrome
  - iterm2
  - keka
  - insomnia
  - raycast
  - slack
  - spotify
  - sublime-text
  - visual-studio-code
  - zoom

osx_script: "files/.osx --no-restart"
